name: Build LaTeX Document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/xu-cheng/texlive-full:latest
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode main.tex
          bibtex main
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex
          
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Quantum-RL-Paper.pdf
          path: main.pdf
