name: Build LaTeX Document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/xu-cheng/texlive-full:latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install missing dependencies
        run: |
          apk update
          apk add --no-cache bash coreutils
          
      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode main.tex
          bibtex main
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Quantum-RL-Paper.pdf
          path: main.pdf
