\documentclass[11pt]{quantumpaper}

\title{Quantum Reinforcement Learning:\\ Theoretical Framework and Experimental Results}
\author{Teodor Berger\\ \small{\href{mailto:bergerteodor@google.com}{bergerteodor@google.com}}}
\date{\today}

% Ensure all necessary packages are included
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{amsmath}

\begin{document}

\maketitle

\begin{abstract}
    \input{sections/0_abstract}
\end{abstract}

\section{Introduction}
\label{sec:intro}
\input{sections/1_introduction}

\section{Methodology}
\label{sec:method}
\input{sections/2_methodology}

\section{Experimental Results}
\label{sec:results}
\input{sections/3_results}

\section{Discussion}
\label{sec:discuss}
\input{sections/4_discussion}

% Ensure bibliography is properly configured
\bibliographystyle{plain}
\bibliography{references}

\end{document}
